name: build & publish Docker image
on:
  push:
    tags:
      - '*'
jobs:
  build-and-publish:
    name: lint & publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup Node
        uses: actions/setup-node@v1
      - run: npm install

      - run: npm run lint
      # todo: test

      - name: log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: build Docker image & push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: derhuerst/hamburg-gtfs-rt-server
